# Generated by Django 4.1.7 on 2023-03-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='標題')),
                ('img', models.ImageField(upload_to='uploads', verbose_name='輪播圖片')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '輪播圖片',
                'verbose_name_plural': '輪播圖片',
                'ordering': ('-order', 'id'),
            },
        ),
    ]
