# Generated by Django 4.1.7 on 2023-03-03 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
        migrations.RemoveField(
            model_name='post',
            name='time',
        ),
    ]
