# Generated by Django 4.1.7 on 2023-03-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='標題')),
                ('slug', models.SlugField(max_length=20, unique_for_date='created', verbose_name='短網址')),
                ('location', models.CharField(max_length=120, verbose_name='地點')),
                ('camera', models.CharField(max_length=120, verbose_name='相機型號')),
                ('tags', models.CharField(max_length=50, verbose_name='標籤')),
                ('time', models.IntegerField(default=0, verbose_name='拍攝時間')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '照片內容',
                'verbose_name_plural': '照片內容',
                'ordering': ('id',),
            },
        ),
    ]
