# Generated by Django 4.1.7 on 2023-03-03 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
