# Generated by Django 4.1.7 on 2023-03-05 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_post_tags_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
