# Generated by Django 4.1.7 on 2023-03-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='camera',
            field=models.CharField(blank=True, max_length=120, verbose_name='相機型號'),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=120, verbose_name='地點'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.IntegerField(blank=True, default=0, verbose_name='拍攝時間'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=120, verbose_name='標題'),
        ),
    ]
